roi_tracker:
  window_length: 10
  grid_size: 40
  scaling_factor: 2
  server_addresses: ['http://upoates-tethys.epfl.ch:8000/', 'http://paperino.epfl.ch:8000'] # List of server addresses for remote GPU execution.
  base_kernel_size_xy: 41
  kernel_size_z: 5
  containment_threshold: 0.4
  k: 5.0
  c0: 0.4
  size_ratio_threshold: 0.3
  score_threshold: 0.9
  model_path: "default" # "default" for default path: tracking_tools/weights/*.pth  if another path is given, it will override the default path. 

tracking_runner:
  timeout_ms: 400
  log: True
  log_dir_name: "embryo_tracking"

simulated_microscope:
  max_timeout: 1

